version: "3.9"

services:

  #------------------------- MariaDB -------------------------
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb         # Dockerfile path
      dockerfile: Dockerfile                # Dockerfile name
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped                 # Restart if not stop lol
    expose:                                 # port to expose
      - "3306"

  #------------------------- WORDPRESS -------------------------
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    restart: on-failure
    depends_on:
      - mariadb
    expose:
      - "9000"

  #------------------------- NGINX -------------------------
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    restart: on-failure                     # restart in case of crash
    depends_on:                             # wait for wordpress to start nginx
      - wordpress
    ports:
      - "443:443"

#---------------------------------------------------------------------------------------------------

volumes:

  #------------------------- MARIADB VOLUME -------------------------
  mariadb_volume:
    driver: local                                   # save in local
    driver_opts:
      type: none                                    # no specific type
      o: bind                                       # bind mounts
      device: ${USER_HOME}/data/mariadb_volume      # where to save repo in local
  
  #------------------------- MARIADB VOLUME -------------------------
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USER_HOME}/data/wordpress_volume

#---------------------------------------------------------------------------------------------------

networks:

  inception:
    driver: bridge
    name: inception_network                         # allow the 3 containers t communicate in bridge
